### ISSUE TITLE
Can't access a server installed on another machine

### ISSUE THREAD

**Issue by homayk228** [GenshinNewsRU/PrivateServer#2]
Hello! I installed a server with Mango DB and JDK 17 on the first machine (server on Windows server 2019 x64), on the second (client in my case) - Fiddler to redirect traffic to the server, and off the client.
Problem: I can't get through - using fiddler I see that all requests do not reach, remaining unanswered.
I tried to change the ips in the server config, but it didn't work.
Where do I need to edit so that the server listens not to localhost but to the network card? (all machines are on the local network, 192.168.1.x)

**Comment by de1eteCode** [comment]
You need to in the configuration file.json edit the "accessAddress" parameter

**Comment by mxscowc1ty** [comment]
Hi, just wanted to say that we still don't understand the problem and trying to figure it out. 
Maybe you've got something?

**Comment by honeymiko** [comment]
First of all, hello!

Starting to analyze your problem, most likely the whole problem is in the configuration of the script Fiddler, which just allows you to connect to a private server. Server config, including, also need to configure for the sake of correct addressing.

You may need to configure a firewall on the server itself, which affects the ports.

**Comment by homayk228** [comment]
Ive changed "accessAddress" in "game" and "server" to 192.168.1.117(my server local ip), corrected fiddler script, but nothing changes(fiddler shows me 502 error anyway). Ive changed "bindAddress" in both with my ip, but result is same.Idk what to do(

**Comment by homayk228** [comment]
Inserted a new script into fiddler.Now allow to enter, but white screen, and message "time connection out", in fiddler all good.In server console too.
