### ISSUE TITLE
[Feature Request] Реализация квестов планируется? 

### ISSUE THREAD

**Issue by gamer4eg** [GenshinNewsRU/PrivateServer#3]
Вспоминая с чего начинались пиратки вова в 2007году.
Снифать квесты с офы планируете?

Алсо еще вопрос по магазину- планируется перепилка как на пиратках аллодов(с целью удобства игры)?

**Comment by honeymiko** [comment]
Добрый день! Отвечая на первый вопрос - квесты есть, они присутствуют в самом ядре, но не все рабочие из-за особенностей игры и реализации, в кои мы вдаваться не будем.

По второму вопросу, ответ ещё проще. Мы не являемся официальными разработчиками, сам проект с открытым кодом, если ваш основной язык программирования Java, то просьба брать все исходные файлы [отсюда](https://github.com/Grasscutters/Grasscutter).
